### ISSUE TITLE
`:ViewKeep()` can overwrite data from `:LoadKeep()`

### ISSUE THREAD

**Issue by FireBird702** [noahrepublic/DataKeep#22]
When `:LoadKeep()` and then `:ViewKeep()` is called `:ViewKeep()` gets the original keep (`if Keeps[id] then`), not the copied one. My idea is to not add keep from `:ViewKeep()` to `Keeps` table

**Comment by noahrepublic** [comment]
This was originally on purpose, since the session owns the keep. However I do see some cases this could be confusing, especially since it is not documented.

**Comment by FireBird702** [comment]
> This was originally on purpose, since the session owns the keep. However I do see some cases this could be confusing, especially since it is not documented.

So what should we do? It's a bit strange behavior to me. `ViewKeep()` copies what `:LoadKeep()` already does in this case

**Comment by noahrepublic** [comment]
It should return a view only version, however if possible we should try to reuse the data to save a data request though could be a bad idea incase new globals are added that aren't yet seen on the servers' keep

**Comment by noahrepublic** [comment]
Solved with https://github.com/noahrepublic/DataKeep/issues/22
