### ISSUE TITLE
On `.validate` failure

### ISSUE THREAD

**Issue by noahrepublic** [noahrepublic/DataKeep#27]
When `.validate` fails on save, currently it:

- Does not post the new data to the datastore
- Does *not* revert the data on the keep (so it will continue to fail until the developer changes it)
- Processes an **warning** and fires the `IssueSignal`

This is causing tests to fail, which is ok because we can change the tests, but the part I am worried about is point 2. Do we revert the keep data to the last published data?

**Comment by FireBird702** [comment]
In theory you want it to fail until data changes to be valid and reverting in this case could do more harm than good

**Comment by noahrepublic** [comment]
So you think it is okay how it is? Should the warning be swapped to error?

**Comment by FireBird702** [comment]
I think so. It fails so error might be better

**Comment by noahrepublic** [comment]
On validate failure, what do we do with setting the latest keep? Do we set it to the invalid data?

And when an overwrite is trying to be done but the data is invalid, do we not save, and just release the session

**Comment by FireBird702** [comment]
It is already set to the failed data before `.validate()` so leave it I guess if that's what you mean

**Comment by FireBird702** [comment]
It's 5 am for me so my thinking abilities might be limited rn ;)

**Comment by FireBird702** [comment]
> And when an overwrite is trying to be done but the data is invalid, do we not save, and just release the session

Error, don't save and don't release. Releasing would be weird?

**Comment by noahrepublic** [comment]
> > And when an overwrite is trying to be done but the data is invalid, do we not save, and just release the session
> 
> Error, not save and not release. Releasing would weird?

Will remember to do this tomorrow then
