### ISSUE TITLE
Incorrect Types

### ISSUE THREAD

**Issue by noahrepublic** [noahrepublic/DataKeep#31]
Many reports of typing being wrong, may just need to redo.

**Comment by noahrepublic** [comment]
Previously, I ignored some type errors which I knew weren't affecting anything but couldn't figure out how to resolve them. This time I will write on --!strict and make sure to resolve them

**Comment by noahrepublic** [comment]
[wally-package-types](https://github.com/johnnymorganz/wally-package-types) tool fixes those with no types. Some types are still incorrect.

**Comment by FireBird702** [comment]
https://github.com/noahrepublic/DataKeep/releases/tag/v4.0.0
